# Generated by Django 5.0.6 on 2024-09-15 19:28

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAdvise',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=50, verbose_name='If you liked')),
                ('advice', models.CharField(max_length=50, verbose_name="You'll like")),
                ('description', models.TextField(verbose_name='Additional description')),
                ('category', models.CharField(choices=[('AR', 'Artist'), ('AL', 'Album'), ('TR', 'Track')], default='TR', max_length=10, verbose_name='Advice category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Music advice',
                'verbose_name_plural': 'Music advices',
            },
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
