# Generated by Django 5.0.6 on 2024-09-16 21:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_musicadvise_delete_suggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicAdvise',
            new_name='MusicAdvice',
        ),
    ]
