# Generated by Django 5.0.6 on 2024-09-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_musicadvise_musicadvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicadvice',
            name='advice',
            field=models.CharField(max_length=100, verbose_name="You'll like"),
        ),
        migrations.AlterField(
            model_name='musicadvice',
            name='base',
            field=models.CharField(max_length=100, verbose_name='If you liked'),
        ),
    ]
